STRUCTURE_GUIDES: dict[str, dict] = {
    "classic_timeline": {
        "chapter_strategy": "chronological",
        "typical_chapters": [
            "How We Met",
            "Early Days",
            "Adventures Together",
            "Growing Together",
            "Where We Are Now",
        ],
        "pacing_hint": "Start slow, build momentum, end strong with current-day hero spread.",
        "best_with_vibes": ["romantic_warm", "cinematic_poetic", "bittersweet_lovely"],
        "description": "Your story told in chronological order, from first meeting to now.",
    },
    "milestones": {
        "chapter_strategy": "milestone-based",
        "typical_chapters": [
            "The First Date",
            "The Moment We Knew",
            "Saying Yes",
            "Building Our Home",
            "Today and Tomorrow",
        ],
        "pacing_hint": "Each chapter is a standalone peak moment. Hero spreads dominate.",
        "best_with_vibes": ["romantic_warm", "cinematic_poetic", "minimal_luxury"],
        "description": "Key relationship milestones, each given its own chapter.",
    },
    "trips_adventures": {
        "chapter_strategy": "location-based",
        "typical_chapters": [
            "Our First Trip",
            "Weekend Escapes",
            "The Big Adventure",
            "Hidden Gems",
            "Home Is Wherever You Are",
        ],
        "pacing_hint": "Use location shifts as chapter boundaries. Dense montages for travel clusters.",
        "best_with_vibes": ["playful_meme", "cinematic_poetic", "romantic_warm"],
        "description": "Organized by trips and adventures, from weekend escapes to big journeys.",
    },
    "year_in_love": {
        "chapter_strategy": "seasonal",
        "typical_chapters": [
            "Winter: Cozy Beginnings",
            "Spring: New Growth",
            "Summer: Golden Days",
            "Fall: Deeper Roots",
        ],
        "pacing_hint": "4 chapters, one per season. Balanced density across seasons.",
        "best_with_vibes": ["romantic_warm", "bittersweet_lovely", "cinematic_poetic"],
        "description": "A year of memories organized by season.",
    },
    "first_message_to_now": {
        "chapter_strategy": "communication-milestones",
        "typical_chapters": [
            "The First Message",
            "Late Night Conversations",
            "Meeting IRL",
            "Inside Jokes & Code Words",
            "Us Now",
        ],
        "pacing_hint": "Start with text/screenshot style spreads, transition to photo-heavy. Modern feel.",
        "best_with_vibes": ["playful_meme", "romantic_warm", "comic_illustrated"],
        "description": "From the first DM to today, tracing your digital-to-real love story.",
    },
    "inside_jokes_quotes": {
        "chapter_strategy": "thematic-snippets",
        "typical_chapters": [
            "Things Only We Understand",
            "Our Catchphrases",
            "The Memes That Define Us",
            "Words That Stuck",
            "Why We Work",
        ],
        "pacing_hint": "Short, punchy chapters. Quote-heavy layouts. Less narrative, more vibe.",
        "best_with_vibes": ["playful_meme", "comic_illustrated", "minimal_luxury"],
        "description": "A collection of the phrases, jokes, and quotes that define your relationship.",
    },
    "letters_to_you": {
        "chapter_strategy": "epistolary",
        "typical_chapters": [
            "Dear You, From The Start",
            "Things I Never Said",
            "What I Love About Us",
            "My Favorite Version of You",
            "Here's to Forever",
        ],
        "pacing_hint": "Text-heavy chapters with COLLAGE_PLUS_LETTER spreads. Intimate, personal.",
        "best_with_vibes": ["romantic_warm", "bittersweet_lovely", "cinematic_poetic"],
        "description": "A series of heartfelt letters written to your partner.",
    },
    "scrapbook_collage": {
        "chapter_strategy": "freeform",
        "typical_chapters": [
            "The Messy Beautiful Beginning",
            "Random Tuesdays",
            "Our People",
            "Tiny Moments, Big Feelings",
            "More of This, Please",
        ],
        "pacing_hint": "Dense, collage-heavy layouts. Stickers/doodles encouraged. Organized chaos.",
        "best_with_vibes": ["playful_meme", "comic_illustrated", "romantic_warm"],
        "description": "A freeform scrapbook bursting with personality and organized chaos.",
    },
    "comic_highlights": {
        "chapter_strategy": "episode-based",
        "typical_chapters": [
            "Origin Story",
            "The Sidekick Arc",
            "Boss Battle: Long Distance",
            "Power-Up: Moving In",
            "Post-Credits Scene",
        ],
        "pacing_hint": "Comic-panel style layouts. Narrator boxes between clusters. Hero splash pages.",
        "best_with_vibes": ["comic_illustrated", "playful_meme"],
        "description": "Your love story told as comic book episodes with narrator boxes and splash pages.",
    },
}
